# -*- coding: utf-8 -*-
"""hayah ashraf.a

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fRqbcO6-8aoaTQlhbwX1TSPKalfJ12Hp
"""

1.''' Write a Python function to accept a string value from the user and display the
count of each character in that string. Sample input: Enter a string value:
assembly Sample output: a=1, s=2, e=1, m=1, b=1, l=1, y=1'''

string = input("Enter a string: ")
l1 = ['a','s','e','m','b','l','y']
for char in string:
    if char not in l1:
        l1.append(char)
for item in l1:
 print(item,string.count(item), sep = "=")

2.''' Write a Python function to find the maximum of three numbers Sample input:
34,12,7 Sample output: 34'''

a=10
b=20
c=30
if a>b and a>c:
   print(a,'is the biggest')
elif b>a and b>c:
   print(b,'is the biggest')
else:
   print(c,'is the biggest')

3.''' Write a Python function called exponent(base,exp) that returns an integer
value of base raises to the power of exp. Sample input: Enter the base: 2
Enter the exponent: 3 Sample output: 8'''

base=float(input('enter the base:'))
exp=float(input('enter the exp:'))
int=(base**exp)
print('int value',base**exp)

4.'''Write a Python function that takes a positive integer and returns the sum of
the cube of all the positive integers smaller than the specified number.
Sample input: 4 Sample output: 36. '''

def sum(x):
  sum = 0
  for i in range(1, x):
    sum += i**3
  return sum

print(sum(4))

5.'''Write a Python program which iterates from 1 to 10. For multiples of 2, print
“Fizz” instead of the number and for the multiples of 5, print “Buzz”. For
numbers which are multiples of both 2 and 5, print “FizzBuzz”. Sample input:
numbers from 1 to 10 Sample output: 1 Fizz 3 Fizz Buzz Fizz 7 Fizz 9
FizzBuzz'''

for i in range(1, 11):
  if i % 1 == 0 and i % 2 == 0:
    print("FizzBuzz")
  elif i % 2 == 0:
    print("Fizz")
  elif i % 5 == 0:
    print("Buzz")
  else:
    print(i)

7.''' Write a Python function to find the sum of squares of the numbers in a list.
Sample input: 2,1,3,1 Sample output: 15'''

10.s=0
l1=[2,3,4,5]

for n in l1:
  s=s+n*n
print(s)

8.'''Write a Python program using for loop that will iterate from 1 to 15. For each
iteration, check if the current number is odd or even, and display the message
to the screen as odd or even. Sample input: 1….15 Sample output: 1-odd 2-
even …. 15-odd '''

l1=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
even=[]
odd=[]
while len(l1)>0:
    l=l1.pop()
if l%2==0:
    even.append(l)
else:
    odd.append(l)
print(even)
print(odd)

9.'''asyncWrite a Python function to convert temperatures to and from Celsius
Fahrenheit. [Formula: c/5=f-32/9 where c=temperature in Celsius and f=
temperature in Fahrenheit.] Sample input: Temperature in Fahrenheit =41
Sample output: Temperature in Celsius =5 '''

a=float(input('enter the temperature'))
F=(a*9/5)+32
print('celcius to feherinhit:',(F))

10.'''Write a Python function to calculate the factorial of a number (a nonnegative
integer). The function accepts the number as an argument. Sample input: 3
Sample output: 6 '''

def factorial(x):
  fact=0
  if x<0:
    print("Sorry, factorial does not exist for negative numbers")
  elif num == 0:
   print("The factorial of 0 is 1")
  else:
   for i in range(1,x+1):
       fact+=i
   print("The factorial of",x,"is",fact)
factorial(10)

